add options to facade scripts

diff --git a/basic/.bin/facade/server b/basic/.bin/facade/server
--- a/basic/.bin/facade/server
+++ b/basic/.bin/facade/server
@@ -1,8 +1,50 @@
 #!/usr/bin/zsh
 set -e
 
-if ! find-server; then
-  echo no server running >&2
-  exit 1
+usage() {
+  echo "usage: $0 [-h] [-n] [command]"
+  echo
+  echo 'optional positional argument:'
+  echo '  command        command to be run on the server'
+  echo
+  echo 'optional arguments:'
+  echo '  -h, --help     show this help message and exit'
+  echo '  -n, --no-wait  exit immediately if a server is not found'
+}
+
+error() {
+  echo "$1" >&2
+}
+
+nowait=false
+command=''
+while [ $# -gt 0 ]; do
+  case $1 in
+    -h | --help)
+      usage
+      exit
+    ;;
+    -n | --no-wait)
+      nowait=true
+    ;;
+    -*)
+      error "invalid option: $1"
+      exit 1
+    ;;
+    *)
+      break
+    ;;
+  esac
+  shift
+done
+
+if $nowait && ! find-server; then
+  if ! find-server; then
+    echo no server running >&2
+    exit 1
+  fi
+else
+  while ! find-server; do :; done
 fi
-ssh -o StrictHostKeyChecking=no -o LogLevel=error server
+
+ssh -o StrictHostKeyChecking=no -o LogLevel=error server "$@"
diff --git a/server/.bin/facade/serve b/server/.bin/facade/serve
--- a/server/.bin/facade/serve
+++ b/server/.bin/facade/serve
@@ -1,3 +1,55 @@
 #!/usr/bin/zsh
 
-tmux new -d 'stop-tunnel; start-tunnel'
+usage() {
+  echo "usage: $0 [-h] [-b duration]"
+  echo
+  echo 'optional arguments:'
+  echo '  -h, --help                       show this help message and exit'
+  echo '  -b duration, --backoff duration  wait for <duration> seconds before starting tunnel'
+}
+
+has_argument() {
+  [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*) ]];
+}
+
+extract_argument() {
+  echo "${2:-${1#*=}}"
+}
+
+error() {
+  echo "$1" >&2
+}
+
+before_tunnel=''
+while [ $# -gt 0 ]; do
+  case $1 in
+    -h | --help)
+      usage
+      exit
+    ;;
+    -b | --backoff)
+      if ! has_argument $@; then
+        error 'backoff duration not specified'
+        exit 1
+      fi
+
+      duration=$(extract_argument $@)
+      shift
+
+      before_start+="sleep $duration;"
+    ;;
+    -*)
+      error "invalid option: $1"
+      exit 1
+    ;;
+    *)
+      break
+    ;;
+  esac
+  shift
+done
+
+command='stop-tunnel;'
+command+=$before_start
+command+='start-tunnel'
+tmux new -d $command
